/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bulb.glb -t --transform 
Files: bulb.glb [26.86MB] > /Users/anna.androschuk/react-drei/bulb-transformed.glb [2.26MB] (92%)
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/edison-light-bulb-abab549e6aa846209e8411cd1e135739
Title: Edison light bulb
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
  }
  materials: {
    ['13___Default']: THREE.MeshStandardMaterial
    ['20___Default']: THREE.MeshStandardMaterial
    ['15___Default']: THREE.MeshStandardMaterial
    ['19___Default']: THREE.MeshStandardMaterial
    ['14___Default']: THREE.MeshStandardMaterial
  }
}

export function Bulb(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/bulb-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials['13___Default']} rotation={[0, -0.82, 0.502]} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials['20___Default']} rotation={[0, -0.82, 0.502]} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials['15___Default']} rotation={[0, -0.82, 0.502]} />
      <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials['19___Default']} rotation={[0, -0.82, 0.502]} />
      <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials['14___Default']} rotation={[0, -0.82, 0.502]} />
    </group>
  )
}

useGLTF.preload('/bulb-transformed.glb')
