/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 keyboard.glb --types 
*/

import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { SpecialKeys } from "../utils/KeyMapper";
import { AnimatedKey } from "./AnimatedKey";

export type KeyboardProps = GLTF & {
  nodes: {
    Object_87: THREE.Mesh;
    Object_88: THREE.Mesh;
    Object_89: THREE.Mesh;
    Object_90: THREE.Mesh;
    Object_1: THREE.Mesh;
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_73: THREE.Mesh;
    Object_74: THREE.Mesh;
    Object_75: THREE.Mesh;
    Object_78: THREE.Mesh;
    Object_79: THREE.Mesh;
    Object_81: THREE.Mesh;
    Object_84: THREE.Mesh;
    space: THREE.Mesh;
    back_trail: THREE.Mesh;
    point: THREE.Mesh;
    coma: THREE.Mesh;
    m: THREE.Mesh;
    n: THREE.Mesh;
    b: THREE.Mesh;
    v: THREE.Mesh;
    c: THREE.Mesh;
    x: THREE.Mesh;
    z: THREE.Mesh;
    shift: THREE.Mesh;
    apostrope: THREE.Mesh;
    semicolun: THREE.Mesh;
    l: THREE.Mesh;
    k: THREE.Mesh;
    j: THREE.Mesh;
    h: THREE.Mesh;
    g: THREE.Mesh;
    f: THREE.Mesh;
    d: THREE.Mesh;
    s: THREE.Mesh;
    a: THREE.Mesh;
    caps: THREE.Mesh;
    enter: THREE.Mesh;
    bracket: THREE.Mesh;
    bracket_1: THREE.Mesh;
    p: THREE.Mesh;
    o: THREE.Mesh;
    i: THREE.Mesh;
    u: THREE.Mesh;
    y: THREE.Mesh;
    t: THREE.Mesh;
    r: THREE.Mesh;
    e: THREE.Mesh;
    w: THREE.Mesh;
    q: THREE.Mesh;
    tab: THREE.Mesh;
    backspace: THREE.Mesh;
    sign: THREE.Mesh;
    minus: THREE.Mesh;
    ["0"]: THREE.Mesh;
    ["9"]: THREE.Mesh;
    ["8"]: THREE.Mesh;
    ["7"]: THREE.Mesh;
    ["6"]: THREE.Mesh;
    ["5"]: THREE.Mesh;
    ["4"]: THREE.Mesh;
    ["3"]: THREE.Mesh;
    ["2"]: THREE.Mesh;
    ["1"]: THREE.Mesh;
    yo: THREE.Mesh;
    del: THREE.Mesh;
    base: THREE.Mesh;
    trail: THREE.Mesh;
    shift_1: THREE.Mesh;
  };
  materials: {
    Material_002: THREE.MeshStandardMaterial;
    Mat: THREE.MeshStandardMaterial;
    Material_001: THREE.MeshStandardMaterial;
  };
  meshes: {
    ["mesh"]: THREE.Mesh;
  };
};

export function Keyboard(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/keyboard.glb") as KeyboardProps;

  // useFrame(() => {
  //   if (keyRef.current && pressedKey) {
  //     keyRef.current.position.y -= 0.1;
  //     const timeout = setTimeout(() => {
  //       if (keyRef.current) keyRef.current.position.y += 0.1;
  //     }, 100);
  //     return () => clearTimeout(timeout);
  //   }
  // });

  return (
    <group {...props} dispose={null}>
      <group position={[0.544, 0.016, 0.042]} scale={[5.135, 5.48, 4.966]}>
        <mesh
          geometry={nodes.Object_87.geometry}
          material={materials.Material_002}
          position={[0.021, 0, 0.016]}
        />
        <mesh
          geometry={nodes.Object_88.geometry}
          material={materials.Material_002}
          position={[0.025, 0, 0.016]}
        />
        <mesh
          geometry={nodes.Object_89.geometry}
          material={materials.Material_002}
          position={[0.029, 0, 0.016]}
        />
        <mesh
          geometry={nodes.Object_90.geometry}
          material={materials.Material_002}
          position={[0.025, 0, 0.012]}
        />
        <mesh
          geometry={nodes.Object_1.geometry}
          material={materials.Material_002}
          position={[-0.029, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Material_002}
          position={[-0.021, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Material_002}
          position={[-0.017, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Material_002}
          position={[-0.014, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Material_002}
          position={[-0.01, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Material_002}
          position={[-0.004, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Material_002}
          position={[0, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Material_002}
          position={[0.003, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Material_002}
          position={[0.007, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Material_002}
          position={[0.013, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.Material_002}
          position={[0.016, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Material_002}
          position={[0.02, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Material_002}
          position={[0.024, 0, -0.006]}
        />
        <mesh
          geometry={nodes.Object_73.geometry}
          material={materials.Material_002}
          position={[-0.029, 0, 0.016]}
        />
        <mesh
          geometry={nodes.Object_74.geometry}
          material={materials.Material_002}
          position={[-0.025, 0, 0.016]}
        />
        <mesh
          geometry={nodes.Object_75.geometry}
          material={materials.Material_002}
          position={[-0.021, 0, 0.016]}
        />
        <mesh
          geometry={nodes.Object_78.geometry}
          material={materials.Material_002}
          position={[0.016, 0, 0.016]}
        />
        <mesh
          geometry={nodes.Object_79.geometry}
          material={materials.Material_002}
          position={[0.012, 0, 0.016]}
        />
        <mesh
          geometry={nodes.Object_81.geometry}
          material={materials.Material_002}
          position={[0.029, 0, 0]}
        />
        <mesh
          geometry={nodes.Object_84.geometry}
          material={materials.Material_002}
          position={[0.029, 0, 0.003]}
        />
      </group>
      <AnimatedKey
        relevantKey={SpecialKeys.SPACE}
        geometry={nodes.space.geometry}
        material={materials.Mat}
        position={[0.522, 0.016, 0.121]}
        scale={[43.159, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.BACK_TRAIL}
        geometry={nodes.back_trail.geometry}
        material={materials.Mat}
        position={[0.602, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.POINT}
        geometry={nodes.point.geometry}
        material={materials.Mat}
        position={[0.583, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.COMA}
        geometry={nodes.coma.geometry}
        material={materials.Mat}
        position={[0.564, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="m"
        geometry={nodes.m.geometry}
        material={materials.Mat}
        position={[0.545, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="n"
        geometry={nodes.n.geometry}
        material={materials.Mat}
        position={[0.526, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="b"
        geometry={nodes.b.geometry}
        material={materials.Mat}
        position={[0.507, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="v"
        geometry={nodes.v.geometry}
        material={materials.Mat}
        position={[0.489, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="c"
        geometry={nodes.c.geometry}
        material={materials.Mat}
        position={[0.47, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="x"
        geometry={nodes.x.geometry}
        material={materials.Mat}
        position={[0.451, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="z"
        geometry={nodes.z.geometry}
        material={materials.Mat}
        position={[0.431, 0.016, 0.1]}
        scale={[5.135, 5.48, 4.966]}
      />
      <mesh
        geometry={nodes.shift.geometry}
        material={materials.Mat}
        position={[0.404, 0.016, 0.1]}
        scale={[9.445, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.APOSTROPHE}
        geometry={nodes.apostrope.geometry}
        material={materials.Mat}
        position={[0.621, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.SEMICOLON}
        geometry={nodes.semicolun.geometry}
        material={materials.Mat}
        position={[0.601, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="1"
        geometry={nodes.l.geometry}
        material={materials.Mat}
        position={[0.582, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="k"
        geometry={nodes.k.geometry}
        material={materials.Mat}
        position={[0.563, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="j"
        geometry={nodes.j.geometry}
        material={materials.Mat}
        position={[0.544, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="h"
        geometry={nodes.h.geometry}
        material={materials.Mat}
        position={[0.525, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="g"
        geometry={nodes.g.geometry}
        material={materials.Mat}
        position={[0.506, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="f"
        geometry={nodes.f.geometry}
        material={materials.Mat}
        position={[0.487, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="d"
        geometry={nodes.d.geometry}
        material={materials.Mat}
        position={[0.468, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="s"
        geometry={nodes.s.geometry}
        material={materials.Mat}
        position={[0.449, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="a"
        geometry={nodes.a.geometry}
        material={materials.Mat}
        position={[0.43, 0.016, 0.08]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="caps"
        geometry={nodes.caps.geometry}
        material={materials.Mat}
        position={[0.402, 0.016, 0.08]}
        scale={[8.295, 5.48, 4.966]}
      />
      <mesh
        geometry={nodes.enter.geometry}
        material={materials.Mat}
        position={[0.663, 0.016, 0.06]}
        scale={[8.295, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.BRACKET}
        geometry={nodes.bracket.geometry}
        material={materials.Mat}
        position={[0.638, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.BRACKET_1}
        geometry={nodes.bracket_1.geometry}
        material={materials.Mat}
        position={[0.619, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="p"
        geometry={nodes.p.geometry}
        material={materials.Mat}
        position={[0.599, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="o"
        geometry={nodes.o.geometry}
        material={materials.Mat}
        position={[0.58, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="i"
        geometry={nodes.i.geometry}
        material={materials.Mat}
        position={[0.561, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="u"
        geometry={nodes.u.geometry}
        material={materials.Mat}
        position={[0.541, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="y"
        geometry={nodes.y.geometry}
        material={materials.Mat}
        position={[0.522, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="t"
        geometry={nodes.t.geometry}
        material={materials.Mat}
        position={[0.502, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="r"
        geometry={nodes.r.geometry}
        material={materials.Mat}
        position={[0.484, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="e"
        geometry={nodes.e.geometry}
        material={materials.Mat}
        position={[0.465, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="w"
        geometry={nodes.w.geometry}
        material={materials.Mat}
        position={[0.446, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="q"
        geometry={nodes.q.geometry}
        material={materials.Mat}
        position={[0.427, 0.016, 0.06]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="tab"
        geometry={nodes.tab.geometry}
        material={materials.Mat}
        position={[0.402, 0.016, 0.06]}
        scale={[8.295, 5.48, 4.966]}
      />
      <mesh
        geometry={nodes.backspace.geometry}
        material={materials.Mat}
        position={[0.662, 0.016, 0.039]}
        scale={[9.142, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.SIGN}
        geometry={nodes.sign.geometry}
        material={materials.Mat}
        position={[0.632, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.MINUS}
        geometry={nodes.minus.geometry}
        material={materials.Mat}
        position={[0.613, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="0"
        geometry={nodes["0"].geometry}
        material={materials.Mat}
        position={[0.593, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="9"
        geometry={nodes["9"].geometry}
        material={materials.Mat}
        position={[0.573, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="8"
        geometry={nodes["8"].geometry}
        material={materials.Mat}
        position={[0.553, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="7"
        geometry={nodes["7"].geometry}
        material={materials.Mat}
        position={[0.534, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="6"
        geometry={nodes["6"].geometry}
        material={materials.Mat}
        position={[0.514, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="5"
        geometry={nodes["5"].geometry}
        material={materials.Mat}
        position={[0.494, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="4"
        geometry={nodes["4"].geometry}
        material={materials.Mat}
        position={[0.475, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="3"
        geometry={nodes["3"].geometry}
        material={materials.Mat}
        position={[0.456, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="2"
        geometry={nodes["2"].geometry}
        material={materials.Mat}
        position={[0.436, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey="1"
        geometry={nodes["1"].geometry}
        material={materials.Mat}
        position={[0.417, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <AnimatedKey
        relevantKey={SpecialKeys.YO}
        geometry={nodes.yo.geometry}
        material={materials.Mat}
        position={[0.397, 0.016, 0.039]}
        scale={[5.135, 5.48, 4.966]}
      />
      <mesh
        geometry={nodes.del.geometry}
        material={materials.Mat}
        position={[0.691, 0.016, 0.011]}
        scale={[5.135, 5.48, 4.966]}
      />
      <mesh
        geometry={nodes.base.geometry}
        material={materials.Material_001}
        position={[0.361, 0.112, 0.111]}
        scale={88.551}
      />
      <mesh
        geometry={nodes.trail.geometry}
        material={materials.Mat}
        position={[0.668, 0.016, 0.08]}
        scale={[11.34, 5.48, 4.966]}
      />
      <mesh
        geometry={nodes.shift_1.geometry}
        material={materials.Mat}
        position={[0.636, 0.016, 0.1]}
        scale={[9.445, 5.48, 4.966]}
      />
    </group>
  );
}

useGLTF.preload("/keyboard.glb");
